[frames.A1]
img = "chapter1.png"
width = 50
x = 0
y = 0
rotate = 0

[frames.A2]
img = "chapter2.png"
width = 42
x = 0
y = 0
rotate = 0

[frames.A3]
img = "chapter3.png"
width = 42
x = 0
y = 0
rotate = 0

[frames.A5]
img = "bonus2.png"
width = 127
x = 0
y = 0
rotate = 0

[frames.B1]
img = "chapter4.png"
width = 42
x = 0
y = 0
rotate = 0

[frames.B3]
img = "chapter5.png"
width = 55
x = 0
y = 0
rotate = 0

[frames.B4]
img = "centerpiece.png"
width = 105
x = 0
y = 0
rotate = 0

[frames.B5]
img = "bonus1.png"
width = 88
x = 0
y = 0
rotate = 0