#+ BUTTON SETTINGS

[buttons]
color = "#ffaaff"  # icon color
border_color = "#ffeeff"  # border color
border_opacity = 32  # 0-255
border_width = 2  # in px


#+ GRID SETTINGS
[grid]
speed = 0.7  # in seconds
scale = 100  # in %


#~ background
[grid.bg]
path = "/images/bricks.png"
repeat = "repeat"
size = 420  # in px

#~ frames
[grid.frames.A1]
img = "chapter1.png"
scale = { "width" = 0, "height" = 0 }
x = 0
y = 0
rotate = 0

[grid.frames.A2]
img = "chapter2.png"
scale = { "width" = 0, "height" = 0 }
x = 0
y = 0
rotate = 0

[grid.frames.A3]
img = "chapter3.png"
scale = { "width" = 0, "height" = 0 }
x = 0
y = 0
rotate = 0

[grid.frames.A5]
img = "bonus2.png"
scale = { "width" = 0, "height" = 90 }
x = 0
y = -5
rotate = 0

[grid.frames.B1]
img = "chapter4.png"
scale = { "width" = 0, "height" = 0 }
x = 0
y = 0
rotate = 0

[grid.frames.B3]
img = "chapter5.png"
scale = { "width" = 0, "height" = 0 }
x = 0
y = 0
rotate = 0

[grid.frames.B4]
img = "centerpiece.png"
scale = { "width" = 0, "height" = 0 }
x = 0
y = 0
rotate = 0

[grid.frames.B5]
img = "bonus1.png"
scale = { "width" = 0, "height" = 0 }
x = 0
y = 0
rotate = 0